resources:
  containers:
  - container: nv-bionic-wasm
    image: unoplatform/wasm-build:3.0

jobs:
- job: linux
  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    UNO_EMSDK_VERSION: 1.39.11

  steps:
  - checkout: self
    clean: true
  
  - bash: |
      cd ~
      git clone --branch $UNO_EMSDK_VERSION https://github.com/emscripten-core/emsdk 2>&1
      cd emsdk
      ./emsdk install $UNO_EMSDK_VERSION
      ./emsdk activate $UNO_EMSDK_VERSION

    displayName: 'Setup Emscripten'

  - bash: |
      source ~/emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/BenchmarkDotNet.Annotations/BenchmarkDotNet.Annotations.csproj "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget"
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/BenchmarkDotNet/BenchmarkDotNet.csproj "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget"
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/samples/BenchmarkDotNet.Live/BenchmarkDotNet.Live.Wasm/BenchmarkDotNet.Live.Wasm.csproj

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/samples/BenchmarkDotNet.Live/BenchmarkDotNet.Live.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container
